jobs:
- name: elasticsearch_master
  release: logsearch
  templates:
  - {name: elasticsearch, release: logsearch}
  resource_pool: elasticsearch_master
  update:
    serial: true
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(0) ))
  persistent_disk_pool: elasticsearch_master
  properties:
    elasticsearch:
      node:
        allow_master: true
        allow_data: false
  update:
    serial: false
    canaries: 1
    max_in_flight: 1

- name: haproxy
  instances: 0
  release: logsearch
  templates:
  - { name: haproxy, release: logsearch }
  resource_pool: haproxy
  networks:
  - name: default
  update:
    serial: false
    canaries: 1
    max_in_flight: 1
  properties:
    haproxy:
      backend_servers: (( grab jobs.ingestor.networks.[0].static_ips ))

- name: cluster_monitor
  instances: 0
  release: logsearch
  templates:
  - { release: logsearch, name: queue }
  - { release: logsearch, name: parser }
  - { release: logsearch, name: ingestor_syslog }
  - { release: logsearch, name: elasticsearch }
  - { release: logsearch, name: elasticsearch_config }
  - { release: logsearch, name: curator }
  - { release: logsearch, name: kibana }
  - { release: logsearch, name: nats_to_syslog }
  resource_pool: cluster_monitor
  networks:
  - name: default
  persistent_disk_pool: cluster_monitor
  properties:
    kibana:
      elasticsearch: 127.0.0.1:9200
      port: 5601
    elasticsearch:
      master_hosts: [127.0.0.1]
      cluster_name: monitor
      node:
        allow_master: true
        allow_data: true
    redis:
      host: 127.0.0.1
    curator:
      elasticsearch_host: 127.0.0.1
      elasticsearch_port: 9200
      purge_logs:
        retention_period: 7
    elasticsearch_config:
      elasticsearch:
        host: 127.0.0.1
        port: 9200
      bulk_data_files: []
      templates:
      - shards-and-replicas: "{ \"template\" : \"*\", \"order\" : 99, \"settings\" : { \"number_of_shards\" : 1, \"number_of_replicas\" : 0 } }"
      - index_template: /var/vcap/packages/logsearch-config/default-mappings.json
    logstash_parser:
      filters:
      - filter: filters_pre.conf
        type: builtin
      - filter: /var/vcap/packages/logsearch-config/logstash-filters-default.conf
        type: path
      - filter: /var/vcap/packages/logsearch-config/logstash-filters-metric.conf
        type: path
      - filter: filters_post.conf
        type: builtin
      - filter: /var/vcap/packages/logsearch-config/if_it_looks_like_json.conf
        type: path
      - filter: /var/vcap/packages/logsearch-config/timecop.conf
        type: path
    nats_to_syslog:
      nats:
        subject: ">"
        user: nats
        password: nats-password
        port: 4222
        machines: [10.0.0.6]
      debug: true
      syslog:
        host: 127.0.0.1
        port: 514
    logstash_ingestor:
      syslog:
        port: 514
  update:
    serial: false
    canaries: 1
    max_in_flight: 1

- name: queue
  release: logsearch
  templates:
  - {name: queue, release: logsearch}
  resource_pool: queue
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(3) ))
  persistent_disk_pool: queue
  update:
    serial: true
    canaries: 1
    max_in_flight: 1

- name: kibana
  release: logsearch
  templates:
  - {name: kibana, release: logsearch}
  instances: 1
  resource_pool: kibana
  networks:
  - name: default
  update:
    serial: false
    canaries: 1
    max_in_flight: 1

- name: elasticsearch_data
  release: logsearch
  templates:
  - {name: elasticsearch, release: logsearch}
  resource_pool: elasticsearch_data
  update:
    serial: true
  instances: 2
  networks:
  - name: default
    static_ips: (( static_ips(16, 17) ))
  persistent_disk_pool: elasticsearch_data
  properties:
    elasticsearch:
      node:
        allow_master: false
        allow_data: true
  update:
    serial: false
    canaries: 1
    max_in_flight: 1

- name: ingestor
  release: logsearch
  templates:
  - {name: ingestor_syslog, release: logsearch}
  - {name: ingestor_relp, release: logsearch}
  resource_pool: ingestor
  instances: 1
  networks:
  - name: default
    default: [gateway, dns]
    static_ips: (( static_ips(1) ))
  properties:
    logstash_ingestor:
      debug: false
      relp:
        port: ~
  update:
    serial: false
    canaries: 1
    max_in_flight: 1

- name: parser
  release: logsearch
  templates:
  - {name: parser, release: logsearch}
  - {name: elasticsearch, release: logsearch}
  resource_pool: parser
  instances: 1
  networks:
  - name: default
    static_ips: (( static_ips(4) ))
  update:
    serial: false
    canaries: 1
    max_in_flight: 4

- name: maintenance
  instances: 1
  release: logsearch
  templates:
  - {name: elasticsearch_config, release: logsearch}
  - {name: curator, release: logsearch}
  resource_pool: maintenance
  networks:
  - name: default
  update:
    serial: false
    canaries: 1
    max_in_flight: 1

properties:
  curator:
    elasticsearch_host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
  logstash_parser:
    debug: false
  logstash_ingestor:
    debug: false
  redis:
    host: (( grab jobs.queue.networks.default.static_ips.[0] ))
  elasticsearch:
    log_level: DEBUG
    master_hosts: (( grab jobs.elasticsearch_master.networks.default.static_ips ))
    cluster_name: logsearch
    exec: ~
  kibana:
    elasticsearch: (( concat jobs.elasticsearch_master.networks.default.static_ips.[0] ":9200" ))
  elasticsearch_config:
    elasticsearch:
      host: (( grab jobs.elasticsearch_master.networks.default.static_ips.[0] ))
    templates:
      - index_template: /var/vcap/packages/logsearch-config/default-mappings.json
